### ISSUE TITLE
mrc_anno_to_mrc.py not found 

### ISSUE THREAD

**Issue by demdecuong** [nguyenvulebinh/extractive-qa-mrc#1]
Thank you for your great contributions to Vietnamese QA.

Please update the script for cleaning data : mrc_anno_to_mrc.py

**Comment by demdecuong** [comment]
Does  `mrc_anno_to_mrc` and `squad_to_mrc.py` are the same sir .

**Comment by nguyenvulebinh** [comment]
Yes. I have some typos in my README.md. I fixed that.
